### ISSUE TITLE
java.lang.NoClassDefFoundError: com.adrienleroy.android.R$attr

### ISSUE THREAD

**Issue by adrienleroy** [chrisjenx/Calligraphy#112]
Hello

When launching my app on a samsung galaxy note 2 (4.4.2) it crash on 
CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
                        .setDefaultFontPath(PandroidConfig.DEFAULT_FONT)
                        .setFontAttrId(R.attr.fontPath)
                        .build());

java.lang.NoClassDefFoundError: com.adrienleroy.android.R$attr

Any idea ?

It is weird because it is working on my nexus 5 (5.0.1)

**Comment by chrisjenx** [comment]
@adrienleroy not sure. How is the project included? What version of gradle? build tools version? TargetSdk version etc.. could be a host of things. Have you done a project clean then build?

**Comment by adrienleroy** [comment]
It was an error due to multidex. After configuring the project properly it is working:
http://developer.android.com/tools/building/multidex.html

**Comment by chrisjenx** [comment]
OK great! Thanks @adrienleroy I'll close this then :+1:
